// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data;

#nullable disable

namespace ecommerce.Migrations
{
    [DbContext(typeof(eCommerceDbContext))]
    partial class eCommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Idx_Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "สเปรย์ดับเพลิง"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "ยาแนวรอยต่อ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "ชั้นรถเข็นเล็ก"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "ฉนวนกันความร้อน"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "เทปพันท่อ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "ซิลิโคน"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "สายยาง"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
